### ISSUE TITLE
hone39.table file missing.

### ISSUE THREAD

**Issue by dzorlu** [vocaliodmiku/wav2vec2mdd#2]
Hi- Thank you for open-sourcing your work. 
Quick question. There is a file `hone39.table` that maps L2 phones to TIMIT phones.  Can you share the file as well? 
Deniz

**Comment by vocaliodmiku** [comment]
sorry for missing it, and the file is available now.
ref:
https://kilthub.cmu.edu/ndownloader/files/12101888
https://www.intechopen.com/chapters/15948
