### ISSUE TITLE
pre-training or finetuning?

### ISSUE THREAD

**Issue by MengjieQian** [vocaliodmiku/wav2vec2mdd#3]
Hello, 

Thanks for sharing your work with us. 
I have one question about your configure file, is the configure file for fine-tuning a pre-trained model? Why it is "_name: audio_pretraining" in the task session in the configure file? Also, does it work for any pre-trained Wav2Vec models? Thanks.

Best,
Mengjie

**Comment by vocaliodmiku** [comment]
Oh, this is an old issue about fairseq 0.1.* version. the developer didn't separate finetuning from pretraining in the old version. According the up-to-date version of fairseq, you should use "task._name=audio_finetune". Good luck for u experiment.
